### PR TITLE
Add separator in filter list to visually separate filter options

### PR DESCRIPTION
**Pull request by joeratt**
# Description
Added a separator to the filter list, just to visually separate the options

# Screenshots
Today:
image

With my Change:
image

# Issues
None.

### CODE REVIEW

**Comment by wooojek** [comment]
Hey :) good idea to add separation here, maybe try to use styling instead `&nbsp;`? :) Adding margins to that element would be finite :)

**Comment by joeratt** [comment]
Yep. I should have done that to begin with.

**Comment by joeratt** [comment]
Updated. I'm proposing to use the `mx-auto` bootstrap spacing.

My original spacing issue was that the "Filter by No Comment" was using `mx-2`, from https://github.com/damcclean/hacktoberfest-finder/commit/b351ed6ba70de08a6df7ce9426978ff40cbfbd5a.

 I think `mx-auto` should evenly space all elements in the links portion of the header.

**Comment by damcclean** [comment]
Hey, thanks for your contribution!

However, I'm thinking that it may be better if we just separate the filters somewhere else to kind of tidy up the header.

**Pull request closed without merging**
