### PR TITLE
Possible PWA: 'Cant connect to site' fix

### LINKED ISSUE #118: ✨ PWA opens and displays an error
## Description
When I open Hacktoberfest Finder on my phone after I've added it as a PWA on my homescreen I get an error which says `Can't connect to site`. I'm not 100% what the issue is, can anyone help?

### PR DESCRIPTION
**Pull request by kev1nboer**
Closes #118

### CODE REVIEW

**Comment by kev1nboer** [comment]
I've also updated the colors to match the background!

**Comment by damcclean** [comment]
Hey, thanks again for your contrribution.

**Comment by kev1nboer** [comment]
I wonder if this fixes the issue as I couldn't reproduce it on my device!

**Comment by damcclean** [comment]
Seems to be working fine! I just added it to my phone and my Macbook.

**Pull request merged**
