### PR TITLE
Migrate to fetch

### PR DESCRIPTION
**Pull request by indransyah**
Use fetch instead of axios to reduce the bundle size

### CODE REVIEW

**Comment by damcclean** [comment]
I'll look into merging this later when I get home.

**Comment by damcclean** [comment]
When using Fetch, I don't get any results. The HTTP request seems to work fine, it just doesn't display on the screen.

https://cdn-std.dprcdn.net/files/acc_635918/CWMC8y

**Comment by indransyah** [comment]
Ah, you are right. I know the problem. Let me fix it

**Comment by indransyah** [comment]
It should work now

**Comment by damcclean** [comment]
Awesome! Thanks for your contribution 👍 @indransyah

**Pull request merged**
