### PR TITLE
Back to top button & functionality

### PR DESCRIPTION
**Pull request by pandurijal**
As we discussed on #195 here is my PR.

Screenshot 2020-10-05 at 01 24 11

### CODE REVIEW

**Comment by damcclean** [comment]
Thanks for the pull request!

It looks good, one suggestion if I may: could we add some sort of border to the button or give it a coloured background as you it looks a little strange I think without one.

image

**Comment by Shaddamah** [comment]
Can i also give a suggestion? I think it will look better if it has the same style as the Contribute button!

image

**Comment by AbhinavReddy-Dev** [comment]
@Shaddamah Maybe something that's more gentle to the eyes 🤔?

**Comment by damcclean** [comment]
Yeah, I think using either the blue or the orange/red colour would be work well.

**Comment by pandurijal** [comment]
I adjust some styling guys. Take a look!

Screenshot 2020-10-06 at 21 32 51

**Comment by damcclean** [comment]
Looks good! I'll review and merge this evening!

**Pull request merged**
