### PR TITLE
PurgeCSS 

### PR DESCRIPTION
**Pull request by AbhinavReddy-Dev**
I have added purgeCSS feature #189  in tailwind.config.js file, let me know if that is what was expected. 😁

### CODE REVIEW

**Comment by damcclean** [comment]
Looks good to me. I'll merge it in manually later. Thanks for your contribution!

**Comment by damcclean** [comment]
Thanks again for your contribution! I made a few changes to fix a few issues with the build process and revert some of the indentation.

**Comment by AbhinavReddy-Dev** [comment]
@damcclean bro, I think my contributors.md file didn't get merged properly, maybe because you made few changes and committed.

**Comment by damcclean** [comment]
Ah yeah, for some reason I couldn't get the build working properly when I deployed to Netlify so I moved the work to another branch and reverted it on master. 

I'll add your name to the contributors file now.

**Comment by AbhinavReddy-Dev** [comment]
I too had the same issue so I checked it by deploying my master on Netlify. Anyways, thanks bro, do tag me in case of any issue in the future.

**Pull request merged**
