### PR TITLE
refactor loadIssues using async/await

### PR DESCRIPTION
**Pull request by kristiyan-ASW-G-08**
# Description
Using async/await instead of promises improves readability.

### CODE REVIEW

**Comment by damcclean** [comment]
Just wondering, what is the advantage of doing it this way?

**Comment by kristiyan-ASW-G-08** [comment]
It removes the need for .then blocks making the code more readable. In terms of functionality and performance, there aren't any benefits.

**Comment by damcclean** [comment]
> It removes the need for .then blocks making the code more readable. In terms of functionality and performance, there aren't any benefits.

Ah ok.

Personally, I like using the `.then` and `.catch` stuff so unfortunately I'm not going to merge this pull request 😦 . (it'll still count against your Hacktoberest profile)

Thanks anyway for your contribution, it is appreciated. You're free to contribute to the project on other issues if you'd like 😄

**Comment by kristiyan-ASW-G-08** [comment]
Is there a reason you don't use/like async/await?I'm interested. There aren't any drawbacks as long as you are compiling your code with babel, ts , etc.

**Comment by damcclean** [comment]
To be honest, not really. It's just the way I've always done it.

**Pull request closed without merging**
