### PR TITLE
PurgeCSS | padding | font-size | labels | language Selection | Filter

### PR DESCRIPTION
**Pull request by AbhinavReddy-Dev**
### Made respective changes and made language & filter option working

✅ PurgeCSS added.
✅ Responsiveness tweaks (margin, padding and font-size) for mobile done.
✅ Labels have been added to issue cards.
✅ Language and Filter search enabled.

Please let me know if there is anything else that can be done.😁

### CODE REVIEW

**Comment by AbhinavReddy-Dev** [comment]
App runs as expected on local but when trying to check the above deploy on netlify its very much messed up without CSS.

**Comment by damcclean** [comment]
Thanks for your pull request!

Unfortunately, there's already been mobile fixes and functional filters merged into the app. I'm also not quite sure about displaying labels on the front-end incase it messes with the design.

In the future, would you mind just creating PRs for the stuff with issues related to them, so I can verify if it's something I'd like to be implemented.

I'd happily accept the PurgeCSS stuff but it would have to be as a separate pull request to this one.

Thanks :)

**Comment by AbhinavReddy-Dev** [comment]
Cool, but what about filter options? it was not working when I forked it, so, thought I'd make that change as well.

**Comment by damcclean** [comment]
They were fixed in #190.

**Comment by AbhinavReddy-Dev** [comment]
Okay, I thought labels will give more information regarding the issue and it wasn't messing with the design as well.
Shall I make a PR for PurgeCSS now?

**Comment by damcclean** [comment]
Yeah, we had labels in the cards the previous years with the old design but didn't really like how they were displayed with the different coloured backgrounds...

Yes please 🙂

**Comment by AbhinavReddy-Dev** [comment]
Making a PR right away!

**Comment by AbhinavReddy-Dev** [comment]
Can I make text color changes in the issue card for better hierarchy?

**Comment by damcclean** [comment]
> Can I make text color changes in the issue card for better hierarchy?

Not in the PostCSS card. I'd want to see what you're wanting to change before I agree to merging it in, it could be a good thing for creating an issue about?

**Comment by AbhinavReddy-Dev** [comment]
Yup, I'll create an issue for that.

**Comment by AbhinavReddy-Dev** [comment]
@damcclean can you please mark this with the label hacktoberfest-accepted since I've spent time and efforts to make the changes? I know these weren't in the Issues list but I thought I'd better make them.

**Pull request closed without merging**
