### PR TITLE
Added Service Worker for PWA

### PR DESCRIPTION
**Pull request by dennypradipta**
#105

### CODE REVIEW

**Comment by damcclean** [comment]
Hey, thanks for your contribution! Would you mind fixing the conflict issues then I'll be happy to merge it in 😄

**Comment by damcclean** [comment]
Also, one thing I forgot in the above comment was to add your name and GitHub link to the contributors file.

**Comment by dennypradipta** [comment]
It is done now I think. I added my name in CONTRIBUTORS.MD too.

**Comment by damcclean** [comment]
Thanks for your changes! 🎉

**Pull request merged**
