### PR TITLE
Added last updated year filter, loading indicator, issue count and page indicators

### LINKED ISSUE #185: [FEATURE] - Filter by Year
It would be great if you could filter by year on issues. Currently, I am finding issues from 2 years ago appear there, and those probably wouldn't be as maintained and willing to accept new pull requests.

### PR DESCRIPTION
**Pull request by johnhorsema**
Closes #185 .

- Added last updated year filter
- Added loading indicator
- Added issue count and page number indicators

Screenshot
Screen Shot 2020-10-02 at 6 08 03 PM

### CODE REVIEW

**Comment by damcclean** [comment]
Nice work!

One thing I don't really love is the fact it's a separate box under the existing one. Is there any way we could add it as part of the right 'Newest' and 'No Replies' filter instead?

And might be a good idea to just have the past three years of issues instead?

**Comment by johnhorsema** [comment]
Understand 10 options may be too much. WIll reduce to 3 options.

For the new dropdown row created, please consider the scenario where users can apply multiple filters:
> `No replies` AND `Before 2019-01-01`.

If you put them in the same dropdown, it defeats the purpose of having a multi-field filter.

**Comment by shadowtime2000** [comment]
@johnhorsema Could you change it to after this date instead of before? There doesn't seem to be a purpose of before because 2017 is before 2018 2019 and 2020.

**Comment by johnhorsema** [comment]
> @johnhorsema Could you change it to after this date instead of before? There doesn't seem to be a purpose of before because 2017 is before 2018 2019 and 2020.

Please check the Github Advanced Search feature described in [my issue reply](https://github.com/damcclean/hacktoberfest-finder/issues/185#issuecomment-702614420), it only allows `Updated before this date`.

If you are looking for `After this date`, you will need to fetch all issues from X date onwards and then filter with client-side.

**Comment by damcclean** [comment]
Thanks again for your pull request!

Unfortunately, I think I'm going to close this pull request. I don't really love having a second search bar thingy. Sorry.

However, I think there should be a filter that only displays issues from the current year which I think would make more sense. I'm going to make an issue for that.

**Pull request closed without merging**
